### ISSUE TITLE
Enabling addon error

### ISSUE THREAD

**Issue by SteampunkIslande** [SBCV/Blender-Addon-Photogrammetry-Importer#17]
Hello !
Sorry to bother again, but when I try the latest verison of the addon I have what looks like a circular dependency whenever I enable the addon.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Charles\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer\__init__.py", line 41, in <module>
    modules = developer_utils.setup_addon_modules(__path__, __name__, "bpy" in locals())
  File "C:\Users\Charles\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer\utils\developer_utils.py", line 39, in setup_addon_modules
    modules = import_submodules(names)
  File "C:\Users\Charles\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer\utils\developer_utils.py", line 30, in import_submodules
    modules.append(importlib.import_module("." + name, package_name))
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Charles\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer\utils\opengl_utils.py", line 7, in <module>
    from photogrammetry_importer.opengl.visualization_utils import DrawManager
  File "C:\Users\Charles\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer\opengl\visualization_utils.py", line 7, in <module>
    from photogrammetry_importer.utils.blender_point_utils import compute_particle_coord_texture
ImportError: cannot import name 'compute_particle_coord_texture' from 'photogrammetry_importer.utils.blender_point_utils' (C:\Users\Charles\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer\utils\blender_point_utils.py)

I think the problem is that 'compute_particle_coord_texture' function might be needed in one of its dependencies, thus the error. I am sorry I cannot help more, I don't know the code of this addon.
I would like to help so maybe I will dive into it at some point.

Does it work on your setup ? Maybe blender 2.82 has some slight differences that cause python to look for the wrong modules ?

Thanks in advance !

**Comment by SBCV** [comment]
Thx for reporting this! (Sorry for that)
I've no access to my PC now, but I'll have a look and come back to you!

**Comment by SBCV** [comment]
I could not exactly reproduce that issue, but I ran into a similar error ....
After deleting `C:\Users\<user_name>\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons` I could not reproduce this issue. (Yes, I deleted all addons, but I wanted to be sure ...) 
Thus, I think that this could be caused by old files still remaining in your Blender User folder `(C:\Users\<user_name>\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer).` 
You can check [this link](https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html) to find the corresponding folder for your operating system. 

After clearing the user folder I was able to run the addon on two different machines with Blender 2.81 and 2.82.

Can you check, if that is working for you, and report the results? Since this is potentially a HUGE bug, it would be nice if you could help me out here.

**Comment by SteampunkIslande** [comment]
Your solution worked perfectly ! (even tested the addon with the Sceaux Castle reconstruction from Regard3D and works great).

Also, do you think it would be possible to re-open the issue with Regard3D I openned some weeks ago ? By trying this fix I also had the 'polymorphic_name' key error when importing json. Maybe we could talk about it as general development and not specific issue.

Thanks again for the support, and keep up the good work !

**Comment by SBCV** [comment]
ye sure, just reopen the previous issue (or open a new one) and add some more information about that key error. 
Thx for reporting those errors, these help to improve this addon a lot

**Comment by SBCV** [comment]
One more question: Was it enough to delete `(:\Users\<user_name>\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer` or was it necessary to delete `C:\Users\<user_name>\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons`?

**Comment by SteampunkIslande** [comment]
Sorry, I didn't try only deleting the addon subfolder... I should try later when my addon folder gets messier ^^

**Comment by SBCV** [comment]
No problem ;)
